name: Deploy React App to AWS S3

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: edumanage-dev-website


    steps:
      # Step 1: Checkout Code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the React App
      - name: Build the React app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy build folder to S3
        run: |
          aws s3 sync build/ s3://${{ env.S3_BUCKET }} --delete      