name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js (adjust version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Build project
      - name: Build project
        run: npm run build |
           echo /build

      # 6. Upload build files to S3
      # - name: Deploy to S3
      #   uses: aws-actions/s3-sync@v2
      #   with:
      #     source-dir: build   # adjust if your build folder has a different name
      #     destination-bucket: ${{ secrets.S3_BUCKET_NAME }}
      #   env:
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
